org: radnier
app: api-file-loader
service: api-file-loader
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
